services:
  - type: web
    name: sistema-elecciones
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: true
